/** Supabase Database type definitions for SunEliteHomes */

export interface Database {
  public: {
    Tables: {
      properties: {
        Row: {
          id: number;
          created_at: string;
          updated_at: string;
          title: string;
          ref: string;
          price: number;
          currency: string;
          price_freq: 'sale' | 'month';
          type: string;
          build_year: number | null;
          town: string;
          postcode: string;
          province: string;
          address: string;
          latitude: number | null;
          longitude: number | null;
          beds: number;
          baths: number;
          pool: boolean;
          surface_built: number;
          surface_plot: number;
          energy_consumption: string;
          energy_emissions: string;
          description: string;
          description_zone: string;
          private_notes: string;
          is_public: boolean;
          features: string[];
          status: string;
          images: string[];
          agent_id: string | null;
          owner_contact_id: number | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          title?: string;
          ref?: string;
          price?: number;
          currency?: string;
          price_freq?: 'sale' | 'month';
          type?: string;
          build_year?: number | null;
          town?: string;
          postcode?: string;
          province?: string;
          address?: string;
          latitude?: number | null;
          longitude?: number | null;
          beds?: number;
          baths?: number;
          pool?: boolean;
          surface_built?: number;
          surface_plot?: number;
          energy_consumption?: string;
          energy_emissions?: string;
          description?: string;
          description_zone?: string;
          private_notes?: string;
          is_public?: boolean;
          features?: string[];
          status?: string;
          images?: string[];
          agent_id?: string | null;
          owner_contact_id?: number | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          title?: string;
          ref?: string;
          price?: number;
          currency?: string;
          price_freq?: 'sale' | 'month';
          type?: string;
          build_year?: number | null;
          town?: string;
          postcode?: string;
          province?: string;
          address?: string;
          latitude?: number | null;
          longitude?: number | null;
          beds?: number;
          baths?: number;
          pool?: boolean;
          surface_built?: number;
          surface_plot?: number;
          energy_consumption?: string;
          energy_emissions?: string;
          description?: string;
          description_zone?: string;
          private_notes?: string;
          is_public?: boolean;
          features?: string[];
          status?: string;
          images?: string[];
          agent_id?: string | null;
          owner_contact_id?: number | null;
        };
      };
      contacts: {
        Row: {
          id: number;
          created_at: string;
          updated_at: string;
          first_name: string;
          last_name: string;
          email: string;
          phone: string;
          phone2: string;
          is_owner: boolean;
          is_buyer: boolean;
          owner_intent: string;
          interest_type: string;
          budget_min: number | null;
          budget_max: number | null;
          pref_beds: number | null;
          pref_baths: number | null;
          pref_zones: string[];
          pref_types: string[];
          notes: string;
          source: string;
          status: string;
          agent_id: string | null;
        };
        Insert: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          phone2?: string;
          is_owner?: boolean;
          is_buyer?: boolean;
          owner_intent?: string;
          interest_type?: string;
          budget_min?: number | null;
          budget_max?: number | null;
          pref_beds?: number | null;
          pref_baths?: number | null;
          pref_zones?: string[];
          pref_types?: string[];
          notes?: string;
          source?: string;
          status?: string;
          agent_id?: string | null;
        };
        Update: {
          id?: number;
          created_at?: string;
          updated_at?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          phone2?: string;
          is_owner?: boolean;
          is_buyer?: boolean;
          owner_intent?: string;
          interest_type?: string;
          budget_min?: number | null;
          budget_max?: number | null;
          pref_beds?: number | null;
          pref_baths?: number | null;
          pref_zones?: string[];
          pref_types?: string[];
          notes?: string;
          source?: string;
          status?: string;
          agent_id?: string | null;
        };
      };
      property_interests: {
        Row: {
          id: number;
          property_id: number;
          contact_id: number;
          created_at: string;
          interest_level: string;
          notes: string;
        };
        Insert: {
          id?: number;
          property_id: number;
          contact_id: number;
          created_at?: string;
          interest_level?: string;
          notes?: string;
        };
        Update: {
          id?: number;
          property_id?: number;
          contact_id?: number;
          created_at?: string;
          interest_level?: string;
          notes?: string;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
